budgit/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static


from django.conf import settings

urlpatterns = [  
    path('admin/', admin.site.urls),
    path("", include("frontend.urls")),
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from django.urls import path
from .views import HomeView

app_name = "frontend"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("<str:lang>/", HomeView.as_view(), name="home"),
]

frontend/models.py
from django.db import models


class Intro(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

    def __str__(self):
        return "Intro"

    class Meta:
        verbose_name_plural = "intro"


class AboutUs(models.Model):
    heading = models.TextField()
    content = models.TextField()

    def __str__(self):
        return "About Us"

    class Meta:
        verbose_name_plural = "about us"


class WhatWeDo(models.Model):
    icon = models.ImageField(upload_to="images")
    title = models.CharField(max_length=100)
    content = models.TextField()

    def get_image(self):
        return self.icon.url

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name_plural = "what we do (s)"


class People(models.Model):
    image = models.ImageField(upload_to="images")
    name = models.CharField(max_length=100)
    role = models.CharField(max_length=100)
    content = models.TextField()

    def get_image(self):
        return self.image.url

    def __str__(self):
        return f"{self.name} ({self.role})"

    class Meta:
        verbose_name_plural = "peoples"


class Contact(models.Model):
    address_link = models.CharField(max_length=500)
    address = models.CharField(max_length=200)
    number = models.CharField(max_length=14)
    email = models.EmailField(max_length=254)

    def __str__(self):
        return "Contact"

    class Meta:
        verbose_name_plural = "contact"

frontend/views.py
from django.shortcuts import render
from django.views import View
from .models import Intro, AboutUs, WhatWeDo, People, Contact
from django.conf import settings


class HomeView(View):
    def get(self, request, lang=settings.LANGUAGE_CODE):
        intro = Intro.objects.last()
        about = AboutUs.objects.last()
        what_we_do = WhatWeDo.objects.all().order_by("id")
        people = People.objects.all().order_by("id")
        contact = Contact.objects.last()

        context = {
            "lang": lang,
            "languages": settings.LANGUAGES,
            "intro": intro,
            "about": about,
            "what_we_do": what_we_do,
            "people": people,
            "contact": contact,
        }
        return render(request, "frontend/home_page.html", context)

frontend/templates/frontend/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="rgb(20,79,101)" />

    <meta
      name="Description"
      content="Budgit, people data action, research and policy, arts, tech, oluseun onigbinde, lawal bakare, nada zohdy, iyanuoluwa bolarinwa, OpenGov DC, 1100 13th St NW Suite 800, Washington, DC 20005, info@budgit.us, +1 240-784-36"
    />

    <meta name="Keyword" content="Budgit, people data action, research and policy, arts for civic change, interactive tech, oluseun onigbinde, lawal bakare, nada zohdy, iyanuoluwa bolarinwa" />

    <meta name="Author" content="oluseun onigbinde, lawal bakare, nada zohdy, iyanuoluwa bolarinwa" />

    <link rel="stylesheet" href="{% static 'frontend/css/base.css'%}">
    <link rel="manifest" href="{% static 'frontend/manifest.json'%}" />
    <link rel="shortcut icon" href="{% static 'frontend/images/ico.png'%}" type="image/x-icon">

    <title>Budgit</title>
    
</head>
<body>
    <div id="splash-screen">
        <img src="{% static 'frontend/images/logo.svg' %}" alt="loading" />
    </div>

    {% block content %}
    {% endblock content %}

    <script src="{% static 'frontend/js/base.js'%}"></script>
</body>
</html>

frontend/templates/frontend/home_page.html
{% extends "frontend/base.html" %}
{% load static %}
{% load extras %}

{% block content %}
<main class="home">
    <img class="ln" src="{% static 'frontend/images/ln.png' %}" alt="" />
    <nav class="main-navbar">
        <img id="logo" src="{% static 'frontend/images/logo.svg' %}" alt="logo" />
        <ul class="navs">
            {% for language in languages %}
            {% if language.0 == lang %}
            <li class="link selected"><a href="{% url 'frontend:home' language.0 %}">{{ language.1 }}</a></li>
            {% else %}
            <li class="link"><a href="{% url 'frontend:home' language.0 %}">{{ language.1 }}</a></li>
            {% endif %}

            {% endfor %}

        </ul>
        <ul class="mobile navs">
            {% for language in languages %}
            {% if language.0 == lang %}
            <li class="link selected"><a>{{ language.1 }}</a></li>
            {% endif %}
            {% endfor %}
            <ul>
                {% for language in languages %}
                {% if language.0 != lang %}
                <li class="link"><a href="{% url 'frontend:home' language.0 %}">{{ language.1 }}</a></li>
                {% endif %}
                {% endfor %}
            </ul>
        </ul>
    </nav>
    <header class="main-header">
        <img src="{% static 'frontend/images/pg-bg.png' %}" class="pg-bg" alt="" />
        <div class="content">
            {% if intro %}
            <h1>{% translate text=intro.title %}</h1>
            <h4>{% translate text=intro.content %}</h4>
            {% endif %}
        </div>
    </header>
    <article class="about-us">
        <section class="container">
            <div class="content">
                <h3 class="line">{% translate text="about us" %}</h3>
                {% if about %}
                <h5>{% translate text=about.heading %}</h5>
                <p>{% translate text=about.content %}</p>
                {% endif %}
            </div>
    </article>
    <article class="what-we-do">
        <h3>{% translate text="what we do" %}</h3>
        <section class="content">
            {% if what_we_do %}
            {% for obj in what_we_do %}
            <div class="item">
                <img src="{{ obj.get_image }}" alt="icon" />
                <h2>{% translate text=obj.title %}</h2>
                <p>{% translate text=obj.content %}</p>
            </div>
            {% endfor %}
            {% endif %}
        </section>
    </article>

    <article class="people">
        <section class="container">
            <h3 class="no-line u">{% translate text="people" %}</h3>
            <section class="content">
                {% if people %}
                {% for obj in people %}
                <div class="item">
                    <img src="{{ obj.get_image }}" alt="icon" />
                    <h3 class="no-line c">{{ obj.name }}</h3>
                    <p class="b">{% translate text=obj.role %}</p>
                    <p>{% translate text=obj.content %}</p>
                </div>
                {% endfor %}
                {% endif %}


            </section>
        </section>
    </article>

    <footer class="main-footer">
        <section class="container">
            <div>
                <h6 class="heading">{% translate text="contact" %}</h6>
                {% if contact %}
                <a href="{{ contact.address_link }}" target="_blank" rel="noopener noreferrer">
                    {{contact.address }}
                </a>
                <br><br>
                <a href="tel:{{ contact.number }}">{% translate text=contact.number %}<a>
                        <br>
                        <a href="mailto:{{ contact.email }}">{{ contact.email }}</a>
                        {% endif %}
            </div>
            <div>
                <p>{% translate text="(C) BudgIT USA, 2022. All rights reserved" %}</p>
            </div>
        </section>
    </footer>
</main>
{% endblock content %}